spring:
  datasource:
    url: jdbc:mysql://${AWS_DB_HOST}/${AWS_DB_DATABASE_NAME}?serverTimezone=Asia/Seoul
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}
    driver-class-name: 'com.mysql.cj.jdbc.Driver'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${SECURITY_OAUTH2_GOOGLE_CLIENT_ID}
            clientSecret: ${SECURITY_OAUTH2_GOOGLE_CLIENT_SECRET}
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile

  logging.level:
    org.hibernate.SQL: debug

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}       # AWS IAM AccessKey 적기
      secretKey: ${AWS_SECRET_ACCESS_KEY}   # AWS IAM SecretKey 적기
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    #      dir: S3 디렉토리 이름 # ex) /gyunny
    region:
      static: ap-northeast-2
    stack:
      auto: false



