spring:
  datasource:
    url: jdbc:mysql://${AWS_DB_HOST}/${AWS_DB_DATABASE_NAME}?serverTimezone=Asia/Seoul
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}
    driver-class-name: 'com.mysql.cj.jdbc.Driver'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  logging.level:
    org.hibernate.SQL: debug


#  jwt:
#    secret-key:

#  security:
#    oauth2.client:
#      registration:
#        google:
#          clientId: ${SECURITY_OAUTH2_GOOGLE_CLIENT_ID}
#          clientSecret: ${SECURITY_OAUTH2_GOOGLE_CLIENT_SECRECT}
#          scope:
#            - email
#            - profile