name: fatman-자동화

on:
  push:
    branches:
      - 자동화
  workflow_dispatch: # 브랜치 push 뿐만 아니라 수동 실행도 가능하게 해줌

jobs:
  build:
    runs-on: ubuntu-latest # 깃허브 액션 스크립트가 작동될 OS 환경 지정

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # 프로젝트 코드를 check out

      - name: Set up JDK 17
        uses: actions/setup-java@v2 # 깃허브 액션이 실행될 OS에 Java 설치
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: access to secrets
        working-directory: ../fatman/src/main/resources/env
        run:
          echo "AWS_DB_HOST=$AWS_DB_HOST"  >> .env
          echo "AWS_DB_DATABASE_NAME" >> .env
          echo "AWS_DB_USERNAME" >> .env
          echo "AWS_DB_PASSWORD" >> .env
          
          echo "AWS_S3_BUCKET_NAME" >> .env
          echo "AWS_ACCESS_KEY_ID"  >> .env
          echo "AWS_SECRET_ACCESS_KEY" >> .env

          echo "SECURITY_OAUTH2_GOOGLE_CLIENT_ID" >> .env
          echo "SECURITY_OAUTH2_GOOGLE_CLIENT_SECRET" >> .env
          
        env:
          AWS_DB_HOST: ${{secrets.AWS_DB_HOST}}
          AWS_DB_DATABASE_NAME: ${{secrets.AWS_DB_DATABASE_NAME}}
          MAP_API_KEY: ${{secrets.MAP_API_KEY}}
          AWS_DB_PASSWORD: ${{secrets.AWS_DB_PASSWORD}}
          AWS_S3_BUCKET_NAME: ${{secrets.AWS_S3_BUCKET_NAME}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          SECURITY_OAUTH2_GOOGLE_CLIENT_ID: ${{secrets.SECURITY_OAUTH2_GOOGLE_CLIENT_ID}}
          SECURITY_OAUTH2_GOOGLE_CLIENT_SECRET: ${{secrets.SECURITY_OAUTH2_GOOGLE_CLIENT_SECRET}}

      - name: Grant execute permission for gradlew
        working-directory: ./fatman
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        working-directory: ./fatman
        run: ./gradlew clean build
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2  # 빌드 완료 시간 가져오기
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}" # 빌드 완료 시간 출력하기
        shell: bash
